name: NRFT
version: 1.0
main: com.nrft.Main
api-version: 1.20
description: A registration plugin
author: kirilosck

# commands:
#   code:
#     description: Авторизация на сервере
#     usage: /code <код> Если вы зарегистрированны, код придёт в телеграмм
#     permission: authplugin.code
#     permission-message: §cВы не заригестрированны!

# permissions:
#   myplugin.code:
#     description: Разрешает использование команды /login
#     default: true
